### ISSUE TITLE
[EPIC] Initial Features/Pages List

### ISSUE THREAD

**Issue by nevrending** [nevrending/foob#2]
**Collected from form responses:**
- [ ] E1. We can make a page listing and explaining every fubuki mascots and persona
- [ ] E2. a simple gacha minigame for fun
- [ ] E3. a page for the passionate sucorn to post our message for fubuki
- [ ] E4. section of the website for others to submit how they found out Fubuki
- [ ] E5. a compilation of every fubuki cat moments (also Kurokami-Sama, edit a picture with her furnitures with our names on it)
- [ ] E6. music/songs done by Fubuki, that play in the background while on the website
- [ ] E7. I want to see the information about upcoming (or past) radio streams of Sukondawa
- [x] E8. A soundboard section where we can archive all the foob noises we clip
- [ ] E9. Repository of meme vids/short vids that Fubuki has uploaded
- [ ] E10. Art, meme and inside information

**Comment by nevrending** [comment]
`reserved`

**Comment by nevrending** [comment]
E2. A Sukon have did this (https://gutterland.github.io/). Reaching out for integration.
E8. A Sukon is currently working on this.

Inside information adapt from https://fubukifan.wordpress.com/

**Comment by bempfoobq052021** [comment]
All right, I'm going to design and implement E1.

**Comment by nevrending** [comment]
> All right, I'm going to design and implement E1.

@steelmaker86 has made https://foob.moe/mascots.html , maybe you can check it out and add more/make changes.

**Comment by bempfoobq052021** [comment]
Oh, thank the Lord for that. I'll check it out.

**Comment by nevrending** [comment]
Additional (to be merged with OP and triaged):
- 6. Profile pages, streaming schedule pages, fun facts about Fubuki
- 2. Link to Fubuki's songs (Say!Fanfare, Song by T-Pocket, Chocolate Decoration etc)
and maybe a link to Mito sensei and Foobs sisters?
- 3. You might want to source all of the fanmade gifs/arts you used for the website
